# Import required library
# Load Dataset

In [1]:
import pandas as pd
df=pd.read_csv('wine.csv')

# Analyze your dataset
# Look for missing values
# Look for outliers
# Verify if any pre-processing is required

In [ ]:
print(df.info())#For datatypes and Null count
print(df.describe(include='all')) # For statistics

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Alcohol                       178 non-null    float64
 1   Malicacid                     178 non-null    float64
 2   Ash                           178 non-null    float64
 3   Alcalinity_of_ash             178 non-null    float64
 4   Magnesium                     178 non-null    int64  
 5   Total_phenols                 178 non-null    float64
 6   Flavanoids                    178 non-null    float64
 7   Nonflavanoid_phenols          178 non-null    float64
 8   Proanthocyanins               178 non-null    float64
 9   Color_intensity               178 non-null    float64
 10  Hue                           178 non-null    float64
 11  0D280_0D315_of_diluted_wines  178 non-null    float64
 12  Proline                       178 non-null    int64  
 13  class

In [3]:
uclass=df['class'].unique()
print(uclass)

[1 2 3]


# Store features in X
# Store Labels/Class in Y
# Split Dataset into Training and Test
# To validate Results

In [ ]:
from sklearn.model_selection import train_test_split
Y=df['class']
X=df.drop('class',axis=1)
print(X.head())
print(Y.head())
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2, random_state=42)

   Alcohol  Malicacid   Ash  Alcalinity_of_ash  Magnesium  Total_phenols  \
0    14.23       1.71  2.43               15.6        127           2.80   
1    13.20       1.78  2.14               11.2        100           2.65   
2    13.16       2.36  2.67               18.6        101           2.80   
3    14.37       1.95  2.50               16.8        113           3.85   
4    13.24       2.59  2.87               21.0        118           2.80   

   Flavanoids  Nonflavanoid_phenols  Proanthocyanins  Color_intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   0D280_0D315_of_diluted_wines  Proline  
0                        

# No missing Values
# Variability in columns
# Normailize all columns
# So that all columns have equal contribution in learning
# Use Scikit Library for normalizing

In [ ]:
from sklearn.preprocessing import StandardScaler
import numpy as np
scaler=StandardScaler()
Xs_train=scaler.fit_transform(X_train)#Normalizes Training Data
Xs_test=scaler.fit_transform(X_test)#Normalizes Test Data
print(np.mean(Xs_test,axis=0))
print(np.var(Xs_test,axis=0))

[ 1.01770444e-15  8.63506797e-17 -1.61907524e-15 -1.26442067e-15
 -5.25813960e-16 -2.15876699e-16 -1.23358114e-17  3.63906436e-16
 -6.07538711e-16  3.54654577e-16 -4.70302809e-16 -4.44089210e-16
  1.07938350e-16]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


# Now Train your model

In [25]:
from sklearn.neighbors import KNeighborsClassifier
myclassifier=KNeighborsClassifier(n_neighbors=4)# Define your model
myclassifier.fit(Xs_train,Y_train)#Train your model

KNeighborsClassifier(n_neighbors=4)

# Now do some predictions on Test Data

In [29]:
Y_pred=myclassifier.predict(Xs_test)#Makes class prediction for each sample
print(Y_pred)

[1 1 3 1 2 1 2 3 2 3 1 3 1 3 1 2 2 2 1 2 1 2 2 3 3 3 2 1 2 1 1 2 3 1 1 1]


# Check with metrics if your algorithm is working fine

In [28]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print(f"Accuracy:{accuracy_score(Y_test,Y_pred)}")
print(f"Classifiaction Report:{classification_report(Y_test,Y_pred)}")
print(f"confusion_matrix:{confusion_matrix(Y_test,Y_pred)}")

Accuracy:0.9444444444444444
Classifiaction Report:              precision    recall  f1-score   support

           1       0.93      1.00      0.97        14
           2       1.00      0.86      0.92        14
           3       0.89      1.00      0.94         8

    accuracy                           0.94        36
   macro avg       0.94      0.95      0.94        36
weighted avg       0.95      0.94      0.94        36

confusion_matrix:[[14  0  0]
 [ 1 12  1]
 [ 0  0  8]]
